### ISSUE TITLE
Crash on TYPO3 7.6.10

### ISSUE THREAD

**Issue by cweiske** [hirnsturm/extensionusagefinder#1]
When opening the backend module I get an exception:

```
Uncaught TYPO3 Exception
#1237823695: Argument "loadPrototype" was not registered. (More information)

TYPO3\CMS\Fluid\Core\Parser\Exception thrown in file
/var/www/site/htdocs/typo3_src/typo3/sysext/fluid/Classes/Core/Parser/TemplateParser.php in line 604.
```

**Comment by hirnsturm** [comment]
Thank for your bugreport. This bug is fixed in version 1.4.1:

The new version is available via 
- composer: https://composer.typo3.org/satis.html#!/extensionusagefinder
- TER: https://typo3.org/extensions/repository/view/extensionusagefinder
